<?php

use Illuminate\Database\Seeder;

class StatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('states')->delete();
        
        \DB::table('states')->insert(array (
            0 => 
            array (
                'id' => 1,
                'slug' => 'florida',
                'title' => 'Florida',
                'abbreviation' => 'FL',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Tallahassee',
                'population_2010' => 18801310,
                'population_2016' => 20612439,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            1 => 
            array (
                'id' => 2,
                'slug' => 'kentucky',
                'title' => 'Kentucky',
                'abbreviation' => 'KY',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Frankfort',
                'population_2010' => 4339367,
                'population_2016' => 4436974,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            2 => 
            array (
                'id' => 3,
                'slug' => 'alabama',
                'title' => 'Alabama',
                'abbreviation' => 'AL',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Montgomery',
                'population_2010' => 4779736,
                'population_2016' => 4863300,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            3 => 
            array (
                'id' => 4,
                'slug' => 'alaska',
                'title' => 'Alaska',
                'abbreviation' => 'AK',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Juneau',
                'population_2010' => 710231,
                'population_2016' => 741894,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            4 => 
            array (
                'id' => 5,
                'slug' => 'arizona',
                'title' => 'Arizona',
                'abbreviation' => 'AZ',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Phoenix',
                'population_2010' => 6392017,
                'population_2016' => 6931071,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            5 => 
            array (
                'id' => 6,
                'slug' => 'arkansas',
                'title' => 'Arkansas',
                'abbreviation' => 'AR',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Little Rock',
                'population_2010' => 2915918,
                'population_2016' => 2988248,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            6 => 
            array (
                'id' => 7,
                'slug' => 'california',
                'title' => 'California',
                'abbreviation' => 'CA',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Sacramento',
                'population_2010' => 37253956,
                'population_2016' => 39250017,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            7 => 
            array (
                'id' => 8,
                'slug' => 'colorado',
                'title' => 'Colorado',
                'abbreviation' => 'CO',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Denver',
                'population_2010' => 5029196,
                'population_2016' => 5540545,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            8 => 
            array (
                'id' => 9,
                'slug' => 'connecticut',
                'title' => 'Connecticut',
                'abbreviation' => 'CT',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Hartford',
                'population_2010' => 3574097,
                'population_2016' => 3576452,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            9 => 
            array (
                'id' => 10,
                'slug' => 'delaware',
                'title' => 'Delaware',
                'abbreviation' => 'DE',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Dover',
                'population_2010' => 897934,
                'population_2016' => 952065,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            10 => 
            array (
                'id' => 11,
                'slug' => 'georgia',
                'title' => 'Georgia',
                'abbreviation' => 'GA',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Atlanta',
                'population_2010' => 9687653,
                'population_2016' => 10310371,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            11 => 
            array (
                'id' => 12,
                'slug' => 'hawaii',
                'title' => 'Hawaii',
                'abbreviation' => 'HI',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Honolulu',
                'population_2010' => 1360301,
                'population_2016' => 1428557,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            12 => 
            array (
                'id' => 13,
                'slug' => 'idaho',
                'title' => 'Idaho',
                'abbreviation' => 'ID',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Boise',
                'population_2010' => 1567582,
                'population_2016' => 1683140,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            13 => 
            array (
                'id' => 14,
                'slug' => 'illinois',
                'title' => 'Illinois',
                'abbreviation' => 'IL',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Springfield',
                'population_2010' => 12830632,
                'population_2016' => 12801539,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            14 => 
            array (
                'id' => 15,
                'slug' => 'indiana',
                'title' => 'Indiana',
                'abbreviation' => 'IN',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Indianapolis',
                'population_2010' => 6483802,
                'population_2016' => 6633053,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            15 => 
            array (
                'id' => 16,
                'slug' => 'iowa',
                'title' => 'Iowa',
                'abbreviation' => 'IA',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Des Moines',
                'population_2010' => 3046355,
                'population_2016' => 3134693,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            16 => 
            array (
                'id' => 17,
                'slug' => 'kansas',
                'title' => 'Kansas',
                'abbreviation' => 'KS',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Topeka',
                'population_2010' => 2853118,
                'population_2016' => 2907289,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            17 => 
            array (
                'id' => 18,
                'slug' => 'louisiana',
                'title' => 'Louisiana',
                'abbreviation' => 'LA',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Baton Rouge',
                'population_2010' => 4533372,
                'population_2016' => 4681666,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            18 => 
            array (
                'id' => 19,
                'slug' => 'maine',
                'title' => 'Maine',
                'abbreviation' => 'ME',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Augusta',
                'population_2010' => 1328361,
                'population_2016' => 1331479,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            19 => 
            array (
                'id' => 20,
                'slug' => 'maryland',
                'title' => 'Maryland',
                'abbreviation' => 'MD',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Annapolis',
                'population_2010' => 5773552,
                'population_2016' => 6016447,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            20 => 
            array (
                'id' => 21,
                'slug' => 'massachusetts',
                'title' => 'Massachusetts',
                'abbreviation' => 'MA',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Boston',
                'population_2010' => 6547629,
                'population_2016' => 6811779,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            21 => 
            array (
                'id' => 22,
                'slug' => 'michigan',
                'title' => 'Michigan',
                'abbreviation' => 'MI',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Lansing',
                'population_2010' => 9883640,
                'population_2016' => 9928300,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            22 => 
            array (
                'id' => 23,
                'slug' => 'minnesota',
                'title' => 'Minnesota',
                'abbreviation' => 'MN',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Saint Paul',
                'population_2010' => 5303925,
                'population_2016' => 5519952,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            23 => 
            array (
                'id' => 24,
                'slug' => 'mississippi',
                'title' => 'Mississippi',
                'abbreviation' => 'MS',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Jackson',
                'population_2010' => 2967297,
                'population_2016' => 2988726,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            24 => 
            array (
                'id' => 25,
                'slug' => 'missouri',
                'title' => 'Missouri',
                'abbreviation' => 'MO',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Jefferson City',
                'population_2010' => 5988927,
                'population_2016' => 6093000,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            25 => 
            array (
                'id' => 26,
                'slug' => 'montana',
                'title' => 'Montana',
                'abbreviation' => 'MT',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Helena',
                'population_2010' => 989415,
                'population_2016' => 1042520,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            26 => 
            array (
                'id' => 27,
                'slug' => 'nebraska',
                'title' => 'Nebraska',
                'abbreviation' => 'NE',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Lincoln',
                'population_2010' => 1826341,
                'population_2016' => 1907116,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            27 => 
            array (
                'id' => 28,
                'slug' => 'nevada',
                'title' => 'Nevada',
                'abbreviation' => 'NV',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Carson City',
                'population_2010' => 2700551,
                'population_2016' => 2940058,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            28 => 
            array (
                'id' => 29,
                'slug' => 'new-hampshire',
                'title' => 'New Hampshire',
                'abbreviation' => 'NH',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Concord',
                'population_2010' => 1316470,
                'population_2016' => 1334795,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            29 => 
            array (
                'id' => 30,
                'slug' => 'new-jersey',
                'title' => 'New Jersey',
                'abbreviation' => 'NJ',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Trenton',
                'population_2010' => 8791894,
                'population_2016' => 8944469,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            30 => 
            array (
                'id' => 31,
                'slug' => 'new-mexico',
                'title' => 'New Mexico',
                'abbreviation' => 'NM',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Santa Fe',
                'population_2010' => 2059179,
                'population_2016' => 2081015,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            31 => 
            array (
                'id' => 32,
                'slug' => 'new-york',
                'title' => 'New York',
                'abbreviation' => 'NY',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Albany',
                'population_2010' => 19378102,
                'population_2016' => 19745289,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            32 => 
            array (
                'id' => 33,
                'slug' => 'north-carolina',
                'title' => 'North Carolina',
                'abbreviation' => 'NC',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Raleigh',
                'population_2010' => 9535483,
                'population_2016' => 10146788,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            33 => 
            array (
                'id' => 34,
                'slug' => 'north-dakota',
                'title' => 'North Dakota',
                'abbreviation' => 'ND',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Bismarck',
                'population_2010' => 672591,
                'population_2016' => 757952,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            34 => 
            array (
                'id' => 35,
                'slug' => 'ohio',
                'title' => 'Ohio',
                'abbreviation' => 'OH',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Columbus',
                'population_2010' => 11536504,
                'population_2016' => 11614373,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            35 => 
            array (
                'id' => 36,
                'slug' => 'oklahoma',
                'title' => 'Oklahoma',
                'abbreviation' => 'OK',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Oklahoma City',
                'population_2010' => 3751351,
                'population_2016' => 3923561,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            36 => 
            array (
                'id' => 37,
                'slug' => 'oregon',
                'title' => 'Oregon',
                'abbreviation' => 'OR',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Salem',
                'population_2010' => 3831074,
                'population_2016' => 4093465,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            37 => 
            array (
                'id' => 38,
                'slug' => 'pennsylvania',
                'title' => 'Pennsylvania',
                'abbreviation' => 'PA',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Harrisburg',
                'population_2010' => 12702379,
                'population_2016' => 12784227,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            38 => 
            array (
                'id' => 39,
                'slug' => 'rhode-island',
                'title' => 'Rhode Island',
                'abbreviation' => 'RI',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Providence',
                'population_2010' => 1052567,
                'population_2016' => 1056426,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            39 => 
            array (
                'id' => 40,
                'slug' => 'south-carolina',
                'title' => 'South Carolina',
                'abbreviation' => 'SC',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Columbia',
                'population_2010' => 4625364,
                'population_2016' => 4961119,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            40 => 
            array (
                'id' => 41,
                'slug' => 'south-dakota',
                'title' => 'South Dakota',
                'abbreviation' => 'SD',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Pierre',
                'population_2010' => 814180,
                'population_2016' => 865454,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            41 => 
            array (
                'id' => 42,
                'slug' => 'tennessee',
                'title' => 'Tennessee',
                'abbreviation' => 'TN',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Nashville',
                'population_2010' => 6346105,
                'population_2016' => 6651194,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            42 => 
            array (
                'id' => 43,
                'slug' => 'texas',
                'title' => 'Texas',
                'abbreviation' => 'TX',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Austin',
                'population_2010' => 25145561,
                'population_2016' => 27862596,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            43 => 
            array (
                'id' => 44,
                'slug' => 'utah',
                'title' => 'Utah',
                'abbreviation' => 'UT',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Salt Lake City',
                'population_2010' => 2763885,
                'population_2016' => 3051217,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            44 => 
            array (
                'id' => 45,
                'slug' => 'vermont',
                'title' => 'Vermont',
                'abbreviation' => 'VT',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Montpelier',
                'population_2010' => 625741,
                'population_2016' => 624594,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            45 => 
            array (
                'id' => 46,
                'slug' => 'virginia',
                'title' => 'Virginia',
                'abbreviation' => 'VA',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Richmond',
                'population_2010' => 8001024,
                'population_2016' => 8411808,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            46 => 
            array (
                'id' => 47,
                'slug' => 'washington',
                'title' => 'Washington',
                'abbreviation' => 'WA',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Olympia',
                'population_2010' => 6724540,
                'population_2016' => 7288000,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            47 => 
            array (
                'id' => 48,
                'slug' => 'west-virginia',
                'title' => 'West Virginia',
                'abbreviation' => 'WV',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Charleston',
                'population_2010' => 1852994,
                'population_2016' => 1831102,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            48 => 
            array (
                'id' => 49,
                'slug' => 'wisconsin',
                'title' => 'Wisconsin',
                'abbreviation' => 'WI',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Madison',
                'population_2010' => 5686986,
                'population_2016' => 5778708,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            49 => 
            array (
                'id' => 50,
                'slug' => 'wyoming',
                'title' => 'Wyoming',
                'abbreviation' => 'WY',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => 'Cheyenne',
                'population_2010' => 563626,
                'population_2016' => 585501,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            50 => 
            array (
                'id' => 51,
                'slug' => 'dc',
                'title' => 'District of Columbia',
                'abbreviation' => 'DC',
                'description' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'capital' => NULL,
                'population_2010' => 601723,
                'population_2016' => 681170,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
        ));
        
        
    }
}