<?php

use Illuminate\Database\Seeder;

class StatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('states')->delete();
        
        \DB::table('states')->insert(array(
            0 =>
            array(
                'id' => 1,
                'slug' => 'florida',
                'title' => 'Florida',
                'abbreviation' => 'FL',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Tallahassee',
                'population_2010' => 18801310,
                'population_2016' => 20612439,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            1 =>
            array(
                'id' => 2,
                'slug' => 'kentucky',
                'title' => 'Kentucky',
                'abbreviation' => 'KY',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Frankfort',
                'population_2010' => 4339367,
                'population_2016' => 4436974,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            2 =>
            array(
                'id' => 3,
                'slug' => 'alabama',
                'title' => 'Alabama',
                'abbreviation' => 'AL',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Montgomery',
                'population_2010' => 4779736,
                'population_2016' => 4863300,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            3 =>
            array(
                'id' => 4,
                'slug' => 'alaska',
                'title' => 'Alaska',
                'abbreviation' => 'AK',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Juneau',
                'population_2010' => 710231,
                'population_2016' => 741894,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            4 =>
            array(
                'id' => 5,
                'slug' => 'arizona',
                'title' => 'Arizona',
                'abbreviation' => 'AZ',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Phoenix',
                'population_2010' => 6392017,
                'population_2016' => 6931071,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            5 =>
            array(
                'id' => 6,
                'slug' => 'arkansas',
                'title' => 'Arkansas',
                'abbreviation' => 'AR',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Little Rock',
                'population_2010' => 2915918,
                'population_2016' => 2988248,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            6 =>
            array(
                'id' => 7,
                'slug' => 'california',
                'title' => 'California',
                'abbreviation' => 'CA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Sacramento',
                'population_2010' => 37253956,
                'population_2016' => 39250017,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            7 =>
            array(
                'id' => 8,
                'slug' => 'colorado',
                'title' => 'Colorado',
                'abbreviation' => 'CO',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Denver',
                'population_2010' => 5029196,
                'population_2016' => 5540545,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            8 =>
            array(
                'id' => 9,
                'slug' => 'connecticut',
                'title' => 'Connecticut',
                'abbreviation' => 'CT',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Hartford',
                'population_2010' => 3574097,
                'population_2016' => 3576452,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            9 =>
            array(
                'id' => 10,
                'slug' => 'delaware',
                'title' => 'Delaware',
                'abbreviation' => 'DE',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Dover',
                'population_2010' => 897934,
                'population_2016' => 952065,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            10 =>
            array(
                'id' => 11,
                'slug' => 'georgia',
                'title' => 'Georgia',
                'abbreviation' => 'GA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Atlanta',
                'population_2010' => 9687653,
                'population_2016' => 10310371,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            11 =>
            array(
                'id' => 12,
                'slug' => 'hawaii',
                'title' => 'Hawaii',
                'abbreviation' => 'HI',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Honolulu',
                'population_2010' => 1360301,
                'population_2016' => 1428557,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            12 =>
            array(
                'id' => 13,
                'slug' => 'idaho',
                'title' => 'Idaho',
                'abbreviation' => 'ID',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Boise',
                'population_2010' => 1567582,
                'population_2016' => 1683140,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            13 =>
            array(
                'id' => 14,
                'slug' => 'illinois',
                'title' => 'Illinois',
                'abbreviation' => 'IL',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Springfield',
                'population_2010' => 12830632,
                'population_2016' => 12801539,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            14 =>
            array(
                'id' => 15,
                'slug' => 'indiana',
                'title' => 'Indiana',
                'abbreviation' => 'IN',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Indianapolis',
                'population_2010' => 6483802,
                'population_2016' => 6633053,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            15 =>
            array(
                'id' => 16,
                'slug' => 'iowa',
                'title' => 'Iowa',
                'abbreviation' => 'IA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Des Moines',
                'population_2010' => 3046355,
                'population_2016' => 3134693,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            16 =>
            array(
                'id' => 17,
                'slug' => 'kansas',
                'title' => 'Kansas',
                'abbreviation' => 'KS',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Topeka',
                'population_2010' => 2853118,
                'population_2016' => 2907289,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            17 =>
            array(
                'id' => 18,
                'slug' => 'louisiana',
                'title' => 'Louisiana',
                'abbreviation' => 'LA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Baton Rouge',
                'population_2010' => 4533372,
                'population_2016' => 4681666,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            18 =>
            array(
                'id' => 19,
                'slug' => 'maine',
                'title' => 'Maine',
                'abbreviation' => 'ME',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Augusta',
                'population_2010' => 1328361,
                'population_2016' => 1331479,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            19 =>
            array(
                'id' => 20,
                'slug' => 'maryland',
                'title' => 'Maryland',
                'abbreviation' => 'MD',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Annapolis',
                'population_2010' => 5773552,
                'population_2016' => 6016447,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            20 =>
            array(
                'id' => 21,
                'slug' => 'massachusetts',
                'title' => 'Massachusetts',
                'abbreviation' => 'MA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Boston',
                'population_2010' => 6547629,
                'population_2016' => 6811779,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            21 =>
            array(
                'id' => 22,
                'slug' => 'michigan',
                'title' => 'Michigan',
                'abbreviation' => 'MI',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Lansing',
                'population_2010' => 9883640,
                'population_2016' => 9928300,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            22 =>
            array(
                'id' => 23,
                'slug' => 'minnesota',
                'title' => 'Minnesota',
                'abbreviation' => 'MN',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Saint Paul',
                'population_2010' => 5303925,
                'population_2016' => 5519952,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            23 =>
            array(
                'id' => 24,
                'slug' => 'mississippi',
                'title' => 'Mississippi',
                'abbreviation' => 'MS',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Jackson',
                'population_2010' => 2967297,
                'population_2016' => 2988726,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            24 =>
            array(
                'id' => 25,
                'slug' => 'missouri',
                'title' => 'Missouri',
                'abbreviation' => 'MO',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Jefferson City',
                'population_2010' => 5988927,
                'population_2016' => 6093000,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            25 =>
            array(
                'id' => 26,
                'slug' => 'montana',
                'title' => 'Montana',
                'abbreviation' => 'MT',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Helena',
                'population_2010' => 989415,
                'population_2016' => 1042520,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            26 =>
            array(
                'id' => 27,
                'slug' => 'nebraska',
                'title' => 'Nebraska',
                'abbreviation' => 'NE',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Lincoln',
                'population_2010' => 1826341,
                'population_2016' => 1907116,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            27 =>
            array(
                'id' => 28,
                'slug' => 'nevada',
                'title' => 'Nevada',
                'abbreviation' => 'NV',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Carson City',
                'population_2010' => 2700551,
                'population_2016' => 2940058,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            28 =>
            array(
                'id' => 29,
                'slug' => 'new-hampshire',
                'title' => 'New Hampshire',
                'abbreviation' => 'NH',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Concord',
                'population_2010' => 1316470,
                'population_2016' => 1334795,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            29 =>
            array(
                'id' => 30,
                'slug' => 'new-jersey',
                'title' => 'New Jersey',
                'abbreviation' => 'NJ',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Trenton',
                'population_2010' => 8791894,
                'population_2016' => 8944469,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            30 =>
            array(
                'id' => 31,
                'slug' => 'new-mexico',
                'title' => 'New Mexico',
                'abbreviation' => 'NM',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Santa Fe',
                'population_2010' => 2059179,
                'population_2016' => 2081015,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            31 =>
            array(
                'id' => 32,
                'slug' => 'new-york',
                'title' => 'New York',
                'abbreviation' => 'NY',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Albany',
                'population_2010' => 19378102,
                'population_2016' => 19745289,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            32 =>
            array(
                'id' => 33,
                'slug' => 'north-carolina',
                'title' => 'North Carolina',
                'abbreviation' => 'NC',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Raleigh',
                'population_2010' => 9535483,
                'population_2016' => 10146788,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            33 =>
            array(
                'id' => 34,
                'slug' => 'north-dakota',
                'title' => 'North Dakota',
                'abbreviation' => 'ND',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Bismarck',
                'population_2010' => 672591,
                'population_2016' => 757952,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            34 =>
            array(
                'id' => 35,
                'slug' => 'ohio',
                'title' => 'Ohio',
                'abbreviation' => 'OH',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Columbus',
                'population_2010' => 11536504,
                'population_2016' => 11614373,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            35 =>
            array(
                'id' => 36,
                'slug' => 'oklahoma',
                'title' => 'Oklahoma',
                'abbreviation' => 'OK',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Oklahoma City',
                'population_2010' => 3751351,
                'population_2016' => 3923561,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            36 =>
            array(
                'id' => 37,
                'slug' => 'oregon',
                'title' => 'Oregon',
                'abbreviation' => 'OR',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Salem',
                'population_2010' => 3831074,
                'population_2016' => 4093465,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            37 =>
            array(
                'id' => 38,
                'slug' => 'pennsylvania',
                'title' => 'Pennsylvania',
                'abbreviation' => 'PA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Harrisburg',
                'population_2010' => 12702379,
                'population_2016' => 12784227,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            38 =>
            array(
                'id' => 39,
                'slug' => 'rhode-island',
                'title' => 'Rhode Island',
                'abbreviation' => 'RI',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Providence',
                'population_2010' => 1052567,
                'population_2016' => 1056426,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            39 =>
            array(
                'id' => 40,
                'slug' => 'south-carolina',
                'title' => 'South Carolina',
                'abbreviation' => 'SC',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Columbia',
                'population_2010' => 4625364,
                'population_2016' => 4961119,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            40 =>
            array(
                'id' => 41,
                'slug' => 'south-dakota',
                'title' => 'South Dakota',
                'abbreviation' => 'SD',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Pierre',
                'population_2010' => 814180,
                'population_2016' => 865454,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            41 =>
            array(
                'id' => 42,
                'slug' => 'tennessee',
                'title' => 'Tennessee',
                'abbreviation' => 'TN',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Nashville',
                'population_2010' => 6346105,
                'population_2016' => 6651194,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            42 =>
            array(
                'id' => 43,
                'slug' => 'texas',
                'title' => 'Texas',
                'abbreviation' => 'TX',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Austin',
                'population_2010' => 25145561,
                'population_2016' => 27862596,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            43 =>
            array(
                'id' => 44,
                'slug' => 'utah',
                'title' => 'Utah',
                'abbreviation' => 'UT',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Salt Lake City',
                'population_2010' => 2763885,
                'population_2016' => 3051217,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            44 =>
            array(
                'id' => 45,
                'slug' => 'vermont',
                'title' => 'Vermont',
                'abbreviation' => 'VT',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Montpelier',
                'population_2010' => 625741,
                'population_2016' => 624594,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            45 =>
            array(
                'id' => 46,
                'slug' => 'virginia',
                'title' => 'Virginia',
                'abbreviation' => 'VA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Richmond',
                'population_2010' => 8001024,
                'population_2016' => 8411808,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            46 =>
            array(
                'id' => 47,
                'slug' => 'washington',
                'title' => 'Washington',
                'abbreviation' => 'WA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Olympia',
                'population_2010' => 6724540,
                'population_2016' => 7288000,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            47 =>
            array(
                'id' => 48,
                'slug' => 'west-virginia',
                'title' => 'West Virginia',
                'abbreviation' => 'WV',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Charleston',
                'population_2010' => 1852994,
                'population_2016' => 1831102,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            48 =>
            array(
                'id' => 49,
                'slug' => 'wisconsin',
                'title' => 'Wisconsin',
                'abbreviation' => 'WI',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Madison',
                'population_2010' => 5686986,
                'population_2016' => 5778708,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            49 =>
            array(
                'id' => 50,
                'slug' => 'wyoming',
                'title' => 'Wyoming',
                'abbreviation' => 'WY',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Cheyenne',
                'population_2010' => 563626,
                'population_2016' => 585501,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            50 =>
            array(
                'id' => 51,
                'slug' => 'dc',
                'title' => 'District of Columbia',
                'abbreviation' => 'DC',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Washington',
                'population_2010' => 601723,
                'population_2016' => 681170,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            51 =>
            array(
                'id' => 52,
                'slug' => 'puerto-rico',
                'title' => 'Puerto Rico',
                'abbreviation' => 'PR',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'San Juan',
                'population_2010' => null,
                'population_2016' => 3411307,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            52 =>
            array(
                'id' => 53,
                'slug' => 'virgin-islands',
                'title' => 'Virgin Islands',
                'abbreviation' => 'VI',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            53 =>
            array(
                'id' => 54,
                'slug' => 'guam',
                'title' => 'Guam',
                'abbreviation' => 'GU',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            54 =>
            array(
                'id' => 55,
                'slug' => 'us-armed-forces-americas',
                'title' => 'US Armed Forces – Americas',
                'abbreviation' => 'AA',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            55 =>
            array(
                'id' => 56,
                'slug' => 'us-armed-forces-europe',
                'title' => 'US Armed Forces – Europe',
                'abbreviation' => 'AE',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            56 =>
            array(
                'id' => 57,
                'slug' => 'us-armed-forces-pacific',
                'title' => 'US Armed Forces – Pacific',
                'abbreviation' => 'AP',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            57 =>
            array(
                'id' => 58,
                'slug' => 'samoa',
                'title' => 'American Samoa',
                'abbreviation' => 'AS',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            58 =>
            array(
                'id' => 59,
                'slug' => 'micronesia',
                'title' => 'Micronesia',
                'abbreviation' => 'FM',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            59 =>
            array(
                'id' => 60,
                'slug' => 'marshall-islands',
                'title' => 'Marshall Islands',
                'abbreviation' => 'MH',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            60 =>
            array(
                'id' => 61,
                'slug' => 'mariana-islands',
                'title' => 'Mariana Islands',
                'abbreviation' => 'MP',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            61 =>
            array(
                'id' => 62,
                'slug' => 'palau',
                'title' => 'Palau',
                'abbreviation' => 'PW',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => null,
                'population_2010' => null,
                'population_2016' => null,
                'country' => 0,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            62 =>
            array(
                'id' => 100,
                'slug' => 'usa',
                'title' => 'United States',
                'abbreviation' => 'US',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Washington DC',
                'population_2010' => 308745538,
                'population_2016' => 322762018,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            63 =>
            array(
                'id' => 101,
                'slug' => 'mexico',
                'title' => 'Mexico',
                'abbreviation' => 'MX',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Mexico City',
                'population_2010' => null,
                'population_2016' => 127540423,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            64 =>
            array(
                'id' => 102,
                'slug' => 'guatemala',
                'title' => 'Guatemala',
                'abbreviation' => 'GT',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Guatemala City',
                'population_2010' => null,
                'population_2016' => 16582469,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            65 =>
            array(
                'id' => 103,
                'slug' => 'belize',
                'title' => 'Belize',
                'abbreviation' => 'BZ',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Belmopan',
                'population_2010' => null,
                'population_2016' => 366954,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            66 =>
            array(
                'id' => 104,
                'slug' => 'honduras',
                'title' => 'Honduras',
                'abbreviation' => 'HN',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Tegucigalpa',
                'population_2010' => null,
                'population_2016' => 9112867,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            67 =>
            array(
                'id' => 105,
                'slug' => 'el-salvador',
                'title' => 'El Salvador',
                'abbreviation' => 'SV',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'San Salvador',
                'population_2010' => null,
                'population_2016' => 6344722,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            68 =>
            array(
                'id' => 106,
                'slug' => 'nicaragua',
                'title' => 'Nicaragua',
                'abbreviation' => 'NI',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Managua',
                'population_2010' => null,
                'population_2016' => 6149928,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            69 =>
            array(
                'id' => 107,
                'slug' => 'costa-rica',
                'title' => 'Costa Rica',
                'abbreviation' => 'CR',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'San Jose',
                'population_2010' => null,
                'population_2016' => 4857274,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            70 =>
            array(
                'id' => 108,
                'slug' => 'panama',
                'title' => 'Panama',
                'abbreviation' => 'PN',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Panama City',
                'population_2010' => null,
                'population_2016' => 4034119,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
            71 =>
            array(
                'id' => 109,
                'slug' => 'columbia',
                'title' => 'Columbia',
                'abbreviation' => 'CB',
                'description' => null,
                'image_id' => null,
                'icon_id' => null,
                'capital' => 'Bogota',
                'population_2010' => null,
                'population_2016' => 49364592,
                'country' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
            ),
        ));
    }
}
