<?php

use Illuminate\Database\Seeder;

class TopicsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('topics')->delete();

        \DB::table('topics')->insert(array(
            0 =>
            array(
                'id' => 1,
                'slug' => 'about',
                'type_id' => null,
                'title' => 'About Drew Roberts',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            1 =>
            array(
                'id' => 2,
                'slug' => 'interviews',
                'type_id' => null,
                'title' => 'Interviews',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            2 =>
            array(
                'id' => 3,
                'slug' => 'projects',
                'type_id' => null,
                'title' => 'Open Source Projects',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            3 =>
            array(
                'id' => 4,
                'slug' => 'markdown',
                'type_id' => null,
                'title' => 'Markdown',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            4 =>
            array(
                'id' => 5,
                'slug' => 'git',
                'type_id' => null,
                'title' => 'Git',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            5 =>
            array(
                'id' => 6,
                'slug' => 'html',
                'type_id' => null,
                'title' => 'HTML',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            6 =>
            array(
                'id' => 7,
                'slug' => 'styling',
                'type_id' => null,
                'title' => 'CSS Styling',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            7 =>
            array(
                'id' => 8,
                'slug' => 'php',
                'type_id' => null,
                'title' => 'PHP',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            8 =>
            array(
                'id' => 9,
                'slug' => 'laravel',
                'type_id' => null,
                'title' => 'Laravel',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            9 =>
            array(
                'id' => 10,
                'slug' => 'javascript',
                'type_id' => null,
                'title' => 'Javascript',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            10 =>
            array(
                'id' => 11,
                'slug' => 'react',
                'type_id' => null,
                'title' => 'React',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            11 =>
            array(
                'id' => 12,
                'slug' => 'vue',
                'type_id' => null,
                'title' => 'Vue',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            12 =>
            array(
                'id' => 13,
                'slug' => 'amp',
                'type_id' => null,
                'title' => 'AMP',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            13 =>
            array(
                'id' => 14,
                'slug' => 'svg',
                'type_id' => null,
                'title' => 'SVG',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
            15 =>
            array(
                'id' => 15,
                'slug' => 'schema',
                'type_id' => null,
                'title' => 'Schema',
                'description' => null,
                'excerpt' => null,
                'note' => null,
                'image_id' => null,
                'icon_id' => null,
                'heroicon_id' => null,
                'poster_id' => null,
                'ogimage_id' => null,
                'content' => null,
                'pageviews' => 0,
                'pageviews_articles' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => null,
            ),
        ));
    }
}
