<?php

use Illuminate\Database\Seeder;

class TopicsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('topics')->delete();

        \DB::table('topics')->insert(array (
            0 =>
            array (
                'id' => 1,
                'slug' => 'interviews',
                'type_id' => NULL,
                'parent_id' => NULL,
                'title' => 'Interviews',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'slug' => 'projects',
                'type_id' => NULL,
                'parent_id' => NULL,
                'title' => 'Open Source Projects',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'slug' => 'markdown',
                'type_id' => NULL,
                'parent_id' => NULL,
                'title' => 'Markdown',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'slug' => 'git',
                'type_id' => NULL,
                'parent_id' => NULL,
                'title' => 'Git',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'slug' => 'html',
                'type_id' => NULL,
                'parent_id' => NULL,
                'title' => 'HTML',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'slug' => 'css',
                'type_id' => NULL,
                'parent_id' => NULL,
                'title' => 'CSS',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'slug' => 'php',
                'type_id' => NULL,
                'parent_id' => 2,
                'title' => 'PHP',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'slug' => 'laravel',
                'type_id' => NULL,
                'parent_id' => 2,
                'title' => 'Laravel',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'slug' => 'javascript',
                'type_id' => NULL,
                'parent_id' => 2,
                'title' => 'Javascript',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'slug' => 'react',
                'type_id' => NULL,
                'parent_id' => 2,
                'title' => 'React',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'slug' => 'vue',
                'type_id' => NULL,
                'parent_id' => 2,
                'title' => 'Vue',
                'description' => NULL,
                'excerpt' => NULL,
                'image_id' => NULL,
                'icon_id' => NULL,
                'heroicon_id' => NULL,
                'cover_id' => NULL,
                'ogimage_id' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2017-11-10 21:48:05',
                'updated_at' => '2017-11-10 21:48:05',
                'deleted_at' => NULL,
            ),
        ));


    }
}
